### ISSUE TITLE
Time Sunrise and Sundown

### ISSUE THREAD

**Issue by CyberSponk** [abaretta/nu.baretta.openweathermap#4]
The Time in the Tags for Sunrise and Sunset are not correct. Seems to be something with the Timezone.

**Homey-Tag**

![image](https://user-images.githubusercontent.com/26149030/45759007-3d1f2d80-bc27-11e8-8f33-ba8471c83a3a.png)

**OpenWeatherSite**

![image](https://user-images.githubusercontent.com/26149030/45759077-63dd6400-bc27-11e8-82ab-14a9e222c560.png)

The Time from OpenWeather seems correct because Sunset is round about 19:30 o'clock.

Homey 1.5.13-RC11, OpenWeatherApp 0.0.10

**Comment by abaretta** [comment]
Hi, thanks for reporting. This will be fixed in v0.0.11.
