### ISSUE TITLE
Subscription issue

### ISSUE THREAD

**Issue by HermanHSlagman** [abaretta/nu.baretta.openweathermap#5]
Dear Anne,

I have tried to fill the form, but I can't write in this form. 
![schermafdruk 2018-11-29 15 44 46](https://user-images.githubusercontent.com/20515850/49230714-9c03de80-f3f0-11e8-8b7c-92fd37cf2dd6.png)

I have used Chrome, Firefox and Safari, all with the same result.

Maybe it's a small issue, but can you help me? 
Thank you in advance.

**Comment by abaretta** [comment]
Do you still have this problem? Were you able to enter a name and the API key? Or is that not possible?
