### ISSUE TITLE
Icons for custom capabilities not working in Homey 2.0.0

### ISSUE THREAD

**Issue by rhannink** [abaretta/nu.baretta.openweathermap#7]
Hello,

With Homey firmware 2.0, the icons for custom capabilities do not show anymore, instead I just see dashed squares. It seems that in Homey 2.0 the custom capabilities have changed, see: [https://apps.developer.athom.com/tutorial-Drivers-Capabilities.html](url)

**Comment by abaretta** [comment]
Thanks. I will look into this when I have migrated to v2 myself.

**Comment by abaretta** [comment]
Fixed in v.0.0.15, will be published shortly.
