### ISSUE TITLE
Inconsistent weather discription

### ISSUE THREAD

**Issue by hplos** [abaretta/nu.baretta.openweathermap#8]
Hoi, volgens mij ben jij ook een Nederlander, dus dan maar in het Nederlands.

Sinds een tijdje gebruik ik je mooie app om het weer te gebruiken als condities in een aantal van mijn flows in m'n homey

Nu zag ik echter dat de beschrijving van het weer niet overeenkomt met de keuzes die je kan maken bij een conditie in een flow.

Zo kan je bijv. alleen kiezen voor bewolkt, maar als ik vervolgens kijk bij het weer, kan deze half bewolkt, zwaar bewolkt e.d. bevatten.

In mijn flow wil ik kijken als het warm is en zonnig ivm de keuze of ik mijn rolluiken dicht moet laten gaan. Dit wil ik bij zonnig weer of bij lichte / halve bewolking.

Ik ben eventueel bereid om mee te helpen bij de ontwikkeling, maar vaak kost het toch nog wel wat tijd om te kijken hoe je 't spul in elkaar hebt gezet....

Vriendelijke groet,
Hans-Peter Los

**Comment by abaretta** [comment]
Let's keep it in english to broaden the audience and avoid duplicate questions.

I used the main categories as defined in https://openweathermap.org/weather-conditions. Using sub-categories (more specific weathercodes) is easy enough, however the accuracy of the data (or lack thereof) is such that I don't think it's very useful. Even if the data were accurate for each location, the data is between 1 to 3 hours old (for the 'current weather' data), hardly useful for home automation in my opinion, except perhaps to randomize the behavior of your home automation. You are probably better of by looking at the output of your solar panels if you have any, or based on a lux measurement or something like that.
 
My 2 cents...
